spring.application.name=smartpizza-ai-analytics-service

server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000